import type { KpiSpec } from "../model/types";

/**
 * Catalogue de KPI — de la DONNÉE, pas du code (docs/09 §1).
 * Chaque définition embarque son contenu pédagogique : définition, interprétation, limites.
 * C'est ce qui rend le produit utilisable par un dirigeant comme par un étudiant.
 */

export const KPI_CATALOG: KpiSpec[] = [
  // ------------------------------------------------------------- croissance
  {
    code: "REVENUE",
    name: "Chiffre d'affaires",
    category: "growth",
    definition: "Total des produits d'exploitation facturés sur la période.",
    formula: "revenue",
    unit: "EUR",
    direction: "UP",
    interpretation:
      "Mesure le volume d'activité. Seul, il ne dit rien de la rentabilité : un CA en hausse peut accompagner une marge en baisse.",
    limits: "Sensible au calendrier de facturation et à la saisonnalité ; comparez à N-1 plutôt qu'au mois précédent.",
  },
  {
    code: "REVENUE_GROWTH",
    name: "Croissance du chiffre d'affaires",
    category: "growth",
    definition: "Variation du chiffre d'affaires par rapport à la période précédente.",
    formula: "(revenue - prev(revenue)) / prev(revenue) * 100",
    unit: "PCT",
    direction: "UP",
    interpretation: "Rythme de progression de l'activité.",
    limits: "Très volatil sur une base mensuelle. Une base faible produit des pourcentages trompeurs.",
  },
  // ------------------------------------------------------------ rentabilité
  {
    code: "CONTRIBUTION_MARGIN",
    name: "Marge sur coûts variables",
    category: "profitability",
    definition: "Chiffre d'affaires diminué des seuls coûts variables.",
    formula: "contributionMargin",
    unit: "EUR",
    direction: "UP",
    interpretation:
      "Ce qui reste pour couvrir les charges fixes. C'est la marge de décision : elle indique si une activité mérite d'être poursuivie.",
    limits: "Dépend de la qualité du classement fixe/variable des charges.",
  },
  {
    code: "MARGIN_RATE",
    name: "Taux de marge sur coûts variables",
    category: "profitability",
    definition: "Marge sur coûts variables rapportée au chiffre d'affaires.",
    formula: "contributionMarginRate",
    unit: "PCT",
    direction: "UP",
    interpretation:
      "Indique la part de chaque euro vendu disponible pour couvrir la structure. Sa baisse est le signal d'alerte le plus précoce.",
    limits: "Un taux stable peut masquer des effets prix et volume qui se compensent : regardez la décomposition.",
  },
  {
    code: "OPERATING_MARGIN_RATE",
    name: "Taux de marge opérationnelle",
    category: "profitability",
    definition: "Résultat d'exploitation rapporté au chiffre d'affaires, après imputation de tous les coûts.",
    formula: "operatingMarginRate",
    unit: "PCT",
    direction: "UP",
    interpretation: "Rentabilité économique de l'activité, structure comprise.",
    limits: "Dépend des clés de répartition retenues : deux méthodes d'affectation donnent deux taux par objet.",
  },
  {
    code: "BREAK_EVEN",
    name: "Seuil de rentabilité",
    category: "profitability",
    definition: "Chiffre d'affaires à partir duquel le résultat devient positif.",
    formula: "breakEven",
    unit: "EUR",
    direction: "DOWN",
    interpretation: "Repère de sécurité : en dessous, l'entreprise perd de l'argent.",
    limits:
      "Suppose un taux de marge sur coûts variables et des charges fixes constants sur la plage d'activité étudiée.",
  },
  {
    code: "SAFETY_MARGIN",
    name: "Marge de sécurité",
    category: "profitability",
    definition: "Écart entre l'activité réalisée et le seuil de rentabilité, en pourcentage.",
    formula: "(revenue - breakEven) / revenue * 100",
    unit: "PCT",
    direction: "UP",
    target: 20,
    warningThreshold: 15,
    criticalThreshold: 5,
    interpretation: "Baisse d'activité supportable avant de passer sous le point mort.",
    limits: "Perd son sens si le taux de marge varie fortement d'une période à l'autre.",
  },
  {
    code: "OPERATING_LEVERAGE",
    name: "Levier opérationnel",
    category: "profitability",
    definition: "Sensibilité du résultat à une variation d'activité.",
    formula: "contributionMargin / operatingMargin",
    unit: "RATIO",
    direction: "DOWN",
    interpretation:
      "Un levier de 4 signifie qu'une baisse de 10 % du chiffre d'affaires réduit le résultat de 40 %.",
    limits: "Instable quand le résultat est proche de zéro ; non calculable en cas de perte.",
  },
  // ------------------------------------------------------------------ coûts
  {
    code: "TOTAL_COST",
    name: "Coûts totaux",
    category: "cost",
    definition: "Ensemble des charges de la période, directes et indirectes.",
    formula: "costTotal",
    unit: "EUR",
    direction: "DOWN",
    interpretation: "Masse de charges à couvrir par l'activité.",
    limits: "À comparer à l'activité, jamais en valeur absolue seule.",
  },
  {
    code: "COST_RATIO",
    name: "Poids des coûts",
    category: "cost",
    definition: "Charges totales rapportées au chiffre d'affaires.",
    formula: "costTotal / revenue * 100",
    unit: "PCT",
    direction: "DOWN",
    interpretation: "Au-dessus de 100 %, l'activité de la période est déficitaire.",
    limits: "Sensible au décalage entre facturation et engagement de charges.",
  },
  {
    code: "FIXED_COST_SHARE",
    name: "Part des coûts fixes",
    category: "cost",
    definition: "Charges fixes rapportées aux charges totales.",
    formula: "fixedCost / costTotal * 100",
    unit: "PCT",
    direction: "DOWN",
    interpretation: "Mesure la rigidité de la structure : plus elle est élevée, plus le levier est fort.",
    limits: "Dépend du classement fixe/variable et de la décomposition des charges semi-variables.",
  },
  {
    code: "PAYROLL_RATIO",
    name: "Poids de la masse salariale",
    category: "cost",
    definition: "Charges de personnel rapportées au chiffre d'affaires.",
    formula: "cost_PAYROLL / revenue * 100",
    unit: "PCT",
    direction: "DOWN",
    interpretation: "Ratio structurant des activités de main-d'œuvre.",
    limits: "Non comparable entre entreprises n'ayant pas le même recours à la sous-traitance.",
  },
  {
    code: "SUBCONTRACTING_RATIO",
    name: "Poids de la sous-traitance",
    category: "cost",
    definition: "Charges de sous-traitance rapportées au chiffre d'affaires.",
    formula: "cost_SUBCONTRACTING / revenue * 100",
    unit: "PCT",
    direction: "DOWN",
    requires: ["subcontractor_tracking"],
    interpretation: "Mesure la part de valeur produite à l'extérieur.",
    limits: "Une hausse peut être un choix de flexibilité, pas nécessairement une dérive.",
  },
  {
    code: "MATERIAL_RATIO",
    name: "Poids des matières",
    category: "cost",
    definition: "Achats de matières rapportés au chiffre d'affaires.",
    formula: "cost_MATERIAL / revenue * 100",
    unit: "PCT",
    direction: "DOWN",
    interpretation: "Sensible aux prix d'achat et au rendement matière.",
    limits: "Ignore les effets de stock si les variations ne sont pas comptabilisées.",
  },
  {
    code: "PURCHASE_RATIO",
    name: "Poids des achats de marchandises",
    category: "cost",
    definition: "Coût d'achat des marchandises vendues rapporté au chiffre d'affaires.",
    formula: "cost_PURCHASE / revenue * 100",
    unit: "PCT",
    direction: "DOWN",
    interpretation: "Complément à 100 de la marge commerciale.",
    limits: "Suppose que les variations de stock sont intégrées.",
  },
  {
    code: "UNIT_COST",
    name: "Coût de revient unitaire",
    category: "cost",
    definition: "Coût total rapporté au nombre d'unités produites.",
    formula: "costTotal / driver_UNITS_PRODUCED",
    unit: "EUR",
    direction: "DOWN",
    requires: ["production_costing"],
    interpretation: "Indicateur central de l'industrie : il agrège matière, main-d'œuvre et structure.",
    limits:
      "Dépend du niveau d'activité : à charges fixes constantes, produire moins augmente mécaniquement le coût unitaire.",
  },
  // ---------------------------------------------------------- productivité
  {
    code: "UTILIZATION",
    name: "Taux d'occupation",
    category: "productivity",
    definition: "Part des heures disponibles effectivement facturables.",
    formula: "driver_BILLABLE_HOURS / driver_AVAILABLE_HOURS * 100",
    unit: "PCT",
    direction: "UP",
    target: 75,
    warningThreshold: 70,
    criticalThreshold: 60,
    requires: ["timesheets"],
    dimensionCode: "EMPLOYEE",
    interpretation: "Sous 70 %, la structure n'est plus couverte par la production vendue.",
    limits: "Ne dit rien du prix : un taux élevé à tarif bas détruit tout de même de la marge.",
  },
  {
    code: "AVG_DAILY_RATE",
    name: "Taux journalier moyen",
    category: "productivity",
    definition: "Chiffre d'affaires rapporté au nombre de jours facturés (base 7 heures).",
    formula: "revenue / (driver_BILLABLE_HOURS / 7)",
    unit: "EUR",
    direction: "UP",
    requires: ["timesheets"],
    interpretation: "Prix de vente moyen d'une journée de production.",
    limits: "Moyenne : elle masque la dispersion entre prestations et le poids des remises.",
  },
  {
    code: "HOURLY_COST",
    name: "Coût horaire de production",
    category: "productivity",
    definition: "Charges de personnel rapportées aux heures travaillées.",
    formula: "cost_PAYROLL / driver_HOURS",
    unit: "EUR",
    direction: "DOWN",
    interpretation: "Base de tout calcul de prix de revient d'une prestation.",
    limits: "N'inclut pas les charges de structure : ce n'est pas un seuil de facturation.",
  },
  {
    code: "REVENUE_PER_FTE",
    name: "Chiffre d'affaires par ETP",
    category: "productivity",
    definition: "Chiffre d'affaires rapporté à l'effectif équivalent temps plein.",
    formula: "revenue / driver_FTE",
    unit: "EUR",
    direction: "UP",
    interpretation: "Productivité apparente du travail.",
    limits: "Dépend du recours à la sous-traitance et de l'intensité capitalistique.",
  },
  {
    code: "MARGIN_PER_FTE",
    name: "Marge par ETP",
    category: "productivity",
    definition: "Marge sur coûts variables rapportée à l'effectif équivalent temps plein.",
    formula: "contributionMargin / driver_FTE",
    unit: "EUR",
    direction: "UP",
    interpretation: "Valeur créée par personne, plus significative que le chiffre d'affaires par ETP.",
    limits: "Sensible au classement des charges variables.",
  },
  {
    code: "OUTPUT_PER_HOUR",
    name: "Production par heure machine",
    category: "productivity",
    definition: "Unités produites rapportées aux heures machine.",
    formula: "driver_UNITS_PRODUCED / driver_MACHINE_HOURS",
    unit: "QTY",
    direction: "UP",
    requires: ["production_costing"],
    interpretation: "Rendement du poste de production.",
    limits: "Non comparable entre produits de complexité différente.",
  },
  // ------------------------------------------------------------- activité
  {
    code: "SCRAP_RATE",
    name: "Taux de rebut",
    category: "activity",
    definition: "Unités rebutées rapportées aux unités produites.",
    formula: "driver_UNITS_SCRAPPED / driver_UNITS_PRODUCED * 100",
    unit: "PCT",
    direction: "DOWN",
    target: 2,
    warningThreshold: 4,
    criticalThreshold: 6,
    requires: ["production_costing"],
    interpretation: "Perte sèche de matière, de temps machine et de capacité.",
    limits: "Ne valorise pas le rebut : deux points de rebut n'ont pas le même coût selon le produit.",
  },
  {
    code: "AVG_TICKET",
    name: "Panier moyen",
    category: "commercial",
    definition: "Chiffre d'affaires rapporté au nombre d'unités vendues.",
    formula: "revenue / driver_UNITS_SOLD",
    unit: "EUR",
    direction: "UP",
    interpretation: "Valeur moyenne d'une transaction.",
    limits: "Moyenne sensible aux ventes exceptionnelles.",
  },
  {
    code: "REVENUE_PER_M2",
    name: "Chiffre d'affaires au m²",
    category: "commercial",
    definition: "Chiffre d'affaires rapporté à la surface de vente.",
    formula: "revenue / driver_M2",
    unit: "EUR",
    direction: "UP",
    requires: ["store_network"],
    dimensionCode: "SITE",
    interpretation: "Référence de comparaison entre points de vente de tailles différentes.",
    limits: "Ignore les différences de zone de chalandise et de mix produit.",
  },
  {
    code: "CLIENT_CONCENTRATION",
    name: "Concentration client",
    category: "commercial",
    definition: "Part du premier client dans le chiffre d'affaires.",
    formula: "topShare_CLIENT",
    unit: "PCT",
    direction: "DOWN",
    target: 25,
    warningThreshold: 35,
    criticalThreshold: 45,
    requires: ["client_profitability"],
    interpretation: "Mesure le risque de dépendance commerciale.",
    limits: "Une concentration élevée peut être assumée dans un modèle de grands comptes.",
  },
  {
    code: "MRR",
    name: "Revenu récurrent mensuel",
    category: "growth",
    definition: "Chiffre d'affaires récurrent rattaché aux contrats de la période.",
    formula: "revenue",
    unit: "EUR",
    direction: "UP",
    requires: ["contract_recurring"],
    dimensionCode: "CONTRACT",
    interpretation: "Base de revenu acquise, indépendante des ventes ponctuelles.",
    limits: "Doit exclure les prestations non récurrentes pour avoir un sens.",
  },
  // -------------------------------------------------------------- projets
  {
    code: "PROGRESS_RATE",
    name: "Avancement moyen",
    category: "project",
    definition: "Avancement des affaires en cours, mesuré physiquement ou par les coûts engagés.",
    formula: "progressPct",
    unit: "PCT",
    direction: "UP",
    requires: ["progress_tracking"],
    interpretation: "Position d'ensemble du portefeuille d'affaires.",
    limits:
      "L'avancement par les coûts (cost-to-cost) surestime l'avancement réel dès qu'une affaire dérive.",
  },
  {
    code: "MARGIN_AT_COMPLETION",
    name: "Marge à terminaison",
    category: "project",
    definition: "Marge projetée à la fin des affaires : prix contractuel moins coût à terminaison.",
    formula: "marginAtCompletion",
    unit: "EUR",
    direction: "UP",
    requires: ["progress_tracking"],
    interpretation: "Seule marge qui compte sur une affaire pluri-périodes.",
    limits: "Dépend de la qualité de l'estimation du reste à faire.",
  },
  {
    code: "COST_TO_COMPLETE",
    name: "Reste à engager",
    category: "project",
    definition: "Coûts restant à engager pour terminer les affaires en cours.",
    formula: "estimateToComplete",
    unit: "EUR",
    direction: "DOWN",
    requires: ["progress_tracking"],
    interpretation: "Engagement futur à financer.",
    limits: "Calculé par extrapolation si aucun reste à faire n'est saisi.",
  },
  {
    code: "EAC_DRIFT",
    name: "Dérive à terminaison",
    category: "project",
    definition: "Écart entre le coût à terminaison projeté et le budget initial.",
    formula: "eacDriftPct",
    unit: "PCT",
    direction: "DOWN",
    target: 0,
    warningThreshold: 3,
    criticalThreshold: 5,
    requires: ["progress_tracking"],
    interpretation: "Signal le plus précoce d'une affaire qui se dégrade.",
    limits: "Peu significatif sous 20 % d'avancement.",
  },
  // --------------------------------------------------------------- budget
  {
    code: "BUDGET_VARIANCE_PCT",
    name: "Écart de chiffre d'affaires vs budget",
    category: "budget",
    definition: "Écart entre le chiffre d'affaires réalisé et le budget, en pourcentage.",
    formula: "(revenue - budget(revenue)) / budget(revenue) * 100",
    unit: "PCT",
    direction: "UP",
    requires: ["budget_control"],
    interpretation: "Position par rapport à l'objectif.",
    limits: "Un budget mal réparti sur l'année crée des écarts mensuels sans signification.",
  },
  {
    code: "BUDGET_CONSUMPTION",
    name: "Consommation du budget de charges",
    category: "budget",
    definition: "Charges réelles rapportées au budget de charges.",
    formula: "costTotal / budget(costTotal) * 100",
    unit: "PCT",
    direction: "DOWN",
    requires: ["budget_control"],
    interpretation: "À comparer au taux d'avancement de l'activité, pas au calendrier.",
    limits: "Ne tient pas compte des engagements non encore facturés.",
  },
  // ------------------------------------------------------------ trésorerie
  {
    code: "CASH_NET",
    name: "Flux de trésorerie net",
    category: "cash",
    definition: "Encaissements diminués des décaissements de la période.",
    formula: "cashNet",
    unit: "EUR",
    direction: "UP",
    requires: ["cash_forecast"],
    interpretation: "Variation réelle de la trésorerie, indépendante du résultat comptable.",
    limits: "Sensible au calendrier des règlements ; à lire sur plusieurs périodes.",
  },
];

export function getKpiSpec(code: string): KpiSpec | undefined {
  return KPI_CATALOG.find((k) => k.code === code);
}

export function kpiCodes(): string[] {
  return KPI_CATALOG.map((k) => k.code);
}
